public with sharing class CaseTriggerHandler {
    
    public static void ifCaseContactIdOrSubjectIsNull(List<Case> newCase){
        // for(Case cs : newCase){
        //     if(cs.ContactId != null && cs.Subject != null){
        //         cs.Priority = 'High';
        //     }
        //     else if(cs.ContactId != null ){
        //         cs.Priority = 'Normal';
        //     }
        //     else if(cs.Subject != null){
        //         cs.Priority = 'Low';
        //     }
        // }
    }
}