public with sharing class ContactTriggerHandler {
    
    public static void updateContact(List<Contact> newContact){
        // List<Contact> listContact = new List<Contact>();
        // for(Contact cont : newContact){
        //     Contact newCon = new Contact(Id = cont.id);
        //     newCon.Description = 'New Description';
        //     listContact.add(newCon);
        // }
        // if(listContact.size() > 0){
        //     UPDATE listContact;
        // }
    }
}